
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./
RUN npm ci || npm install
COPY . .
COPY nginx.conf /etc/nginx/conf.d/default.conf   

ARG BUILD_TIME
ARG VITE_API_BASE
ENV VITE_BUILD_TIME=$BUILD_TIME
ENV VITE_API_BASE=$VITE_API_BASE
RUN npm run build
FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80 8000 8080
CMD ["nginx","-g","daemon off;"]
